// Discipline pilot 0.1. Rules effective 2026-09-29, Asia/Bangkok.
export const VERSION = 'pilot-0.1';
export const DAY = 86400000;
export const RULES = Object.freeze({version: VERSION, effective: '2026-09-29', zone:'Asia/Bangkok', graceMinutes:15,
  tasks: {
    wake:{name:'ตื่นและลุกจากเตียง',pts:20,dueSchool:'07:00',dueHoliday:'08:00',routine:true},
    bed:{name:'เก็บที่นอน',pts:10,dueSchool:'07:10',dueHoliday:'08:10',routine:true},
    school:{name:'พร้อมออกจากบ้านไปโรงเรียน',pts:30,dueSchool:'07:45',schoolOnly:true,routine:true},
    homework:{name:'Homework / assignment',pts:40,dueSchool:'19:00',dueHoliday:'19:00',homeworkOnly:true,routine:true},
    piano:{name:'Piano 20 นาที',pts:50,dueSchool:'20:30',dueHoliday:'20:30',practice:true},
    chess:{name:'Chess 20 นาที',pts:50,dueSchool:'20:30',dueHoliday:'20:30',practice:true},
    taekwondo:{name:'Taekwondo 20 นาที',pts:50,dueSchool:'20:30',dueHoliday:'20:30',practice:true},
    sleep:{name:'เตรียมตัวเสร็จและปิดไฟ',pts:20,dueSchool:'21:00',dueHoliday:'21:00',routine:true}
  },
  rewards:{youtube:{name:'YouTube 30 นาที',cost:100,group:'screen'},game:{name:'เกม 30 นาที',cost:100,group:'screen'},dinner:{name:'เลือก Dinner',cost:300,group:'dinner'},icecream:{name:'Ice cream',cost:300,group:'icecream'},toy200:{name:'ของเล่นงบ 200 บาท',cost:1000,group:'toy'},toy500:{name:'ของเล่นงบ 500 บาท',cost:3000,group:'toy'},toy1000:{name:'ของเล่นงบ 1000 บาท',cost:6000,group:'toy'},sea:{name:'ทะเล',cost:10000,group:'trip'},abroad:{name:'ต่างประเทศ',cost:30000,group:'trip'}}});
const fail = m => {throw Error(m)};
const clone = x => structuredClone(x);
const freshId = () => crypto.randomUUID();
const fmt = new Intl.DateTimeFormat('en-CA',{timeZone:RULES.zone,year:'numeric',month:'2-digit',day:'2-digit'});
export const dayKey = ts => fmt.format(new Date(ts));
const hour = ts => new Intl.DateTimeFormat('en-GB',{timeZone:RULES.zone,hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(ts));
export function bangkokDue(day, hhmm){return Date.parse(`${day}T${hhmm}:00+07:00`)}
export const weekKey = ts => {const day=dayKey(ts),d=new Date(bangkokDue(day,'12:00')); const wd=(d.getUTCDay()+6)%7;return dayKey(bangkokDue(day,'12:00')-wd*DAY)};
const compareDate=(a,b)=>a.localeCompare(b);
export const addMonths = (ts,n) => {const d=new Date(ts+7*3600000),y=d.getUTCFullYear(),m=d.getUTCMonth(),day=d.getUTCDate();const target=new Date(Date.UTC(y,m+n,1));const end=new Date(Date.UTC(target.getUTCFullYear(),target.getUTCMonth()+1,0)).getUTCDate();return Date.UTC(target.getUTCFullYear(),target.getUTCMonth(),Math.min(day,end),d.getUTCHours(),d.getUTCMinutes(),d.getUTCSeconds())-7*3600000};
const LEGACY_TASKS=new Map([['ตื่นนอน ลุกจากเตียง','wake'],['เก็บที่นอนหลังตื่น','bed'],['พร้อมออกจากบ้านไปโรงเรียน','school'],['ทำการบ้านเสร็จ','homework'],['ซ้อม Piano20 นาที','piano']]);
const legacyTaskId=name=>LEGACY_TASKS.get(String(name||'').trim())||null;
function legacyRewardId(name){const n=String(name||'').replace(/\s*\(หารกัน\)\s*$/,'').trim();if(n.includes('Educational YouTube')||n.includes('YouTube 30 นาที'))return 'youtube';if(n.includes('เล่นเกม 30 นาที'))return 'game';if(n.includes('Dinner out'))return 'dinner';if(n.includes('Swensen'))return 'icecream';if(n.includes('ของเล่นงบ 200'))return 'toy200';if(n.includes('ของเล่นงบ 500'))return 'toy500';if(n.includes('ของเล่นงบ 1,000')||n.includes('ของเล่นงบ 1000'))return 'toy1000';return null}
function legacyBankRecord(b,kidId){if(b?.kind!=='deposit'||!b.id||!kidId)return null;const principal=Number(b.amount),rate=Number(b.pct),openedAt=Number(b.openTs),dueAt=Number(b.dueTs);if(!Number.isSafeInteger(principal)||principal<=0||!Number.isFinite(rate)||rate<0||!Number.isFinite(openedAt)||!Number.isFinite(dueAt)||dueAt<=openedAt)return null;return {id:b.id,kidId,principal,original:principal,days:Number(b.days)||Math.round((dueAt-openedAt)/DAY),rate,openedAt,dueAt,status:'open',legacy:true,legacyPot:b.pot||'daily'}}
export function newState(names=['พี่','น้อง']){return {schema:1,version:VERSION,rulesEffective:RULES.effective,kids:names.map((name,i)=>({id:`kid${i+1}`,name,emo:i?'🐻':'🦊',color:i?'#7d9bc1':'#4a6491',pin:i?'2222':'1111',earned:0,borrowed:0,deficit:0,xp:0,eggWarm:0,pets:[],petst:{},adventure:null})),plans:{},ledger:[],requests:[],deposits:[],loans:[],tickets:[],audit:[],migrations:[]}}
export function validate(s){if(s.schema!==1||s.version!==VERSION)fail('ต้องใช้ schema รุ่นทดลอง');for(const k of s.kids){if(!Number.isSafeInteger(k.earned)||!Number.isSafeInteger(k.borrowed)||!Number.isSafeInteger(k.deficit||0)||k.earned<0||k.borrowed<0||(k.deficit||0)<0)fail('ยอดแต้มไม่ถูกต้อง')}return s}
export function mutate(state,fn){if(state.legacy?.blocked)fail('ข้อมูลเก่ายังมีรายการที่ต้องตรวจ ก่อนเริ่มทำรายการด้วยกติกาใหม่');const draft=clone(validate(state));const result=fn(draft);validate(draft);Object.assign(state,draft);return result}
const kid=(s,id)=>s.kids.find(k=>k.id===id)||fail('ไม่พบเด็ก');
const entry=(s,kidId,kind,delta,meta={})=>{const e={id:freshId(),ts:meta.ts??Date.now(),kidId,kind,delta,ruleVersion:VERSION,...meta};s.ledger.push(e);return e};
const audit=(s,action,meta={})=>s.audit.push({id:freshId(),ts:Date.now(),action,...meta});
export const balance=(s,id)=>{const k=kid(s,id);return {available:k.earned+k.borrowed,earned:k.earned,borrowed:k.borrowed,deficit:k.deficit||0,deposits:s.deposits.filter(d=>d.kidId===id&&d.status==='open').reduce((a,d)=>a+d.principal,0),debt:s.loans.filter(l=>l.kidId===id&&l.status==='open').reduce((a,l)=>a+l.remaining,0)}};
function spend(k,n,restricted=false){if(!Number.isSafeInteger(n)||n<0)fail('จำนวนแต้มไม่ถูกต้อง');if(restricted&&k.earned<n)fail('แต้มที่ได้จากงานไม่พอ');if(!restricted&&k.earned+k.borrowed<n)fail('แต้มไม่พอ');const e=Math.min(k.earned,n);k.earned-=e;k.borrowed-=n-e;return {earned:e,borrowed:n-e}}
function refund(k,parts){k.earned+=parts.earned;k.borrowed+=parts.borrowed}
export function setPlan(s,day,{school,homework=false,assignment=''}={}){if(!/^\d{4}-\d{2}-\d{2}$/.test(day)||typeof school!=='boolean')fail('กำหนดวันไม่ถูกต้อง');return mutate(s,d=>{if(d.ledger.some(e=>e.taskDay===day)||d.requests.some(r=>r.day===day))fail('วันนี้เริ่มบันทึกแล้ว');d.plans[day]={school,homework:!!homework,assignment:String(assignment),ruleVersion:VERSION};audit(d,'plan',{day})})}
export function planFor(s,day){return s.plans[day]||{school:[1,2,3,4,5].includes(new Date(bangkokDue(day,'12:00')).getUTCDay()),homework:false,assignment:'',ruleVersion:VERSION}}
export function activeTasks(s,day){const p=planFor(s,day);return Object.entries(RULES.tasks).filter(([,t])=>!t.schoolOnly||p.school).filter(([,t])=>!t.homeworkOnly||p.homework).map(([id,t])=>({id,...t,due:p.school?t.dueSchool:t.dueHoliday}))}
export function scoreTask(s,id,taskId,finishedAt,complete=true){const day=dayKey(finishedAt),t=activeTasks(s,day).find(x=>x.id===taskId)||fail('วันนี้ไม่มีงานนี้');if(!complete)return {points:0,status:'incomplete',day};const due=bangkokDue(day,t.due),late=finishedAt-due;return {points:late<=0?t.pts:late<=RULES.graceMinutes*60000?Math.floor(t.pts/2):0,status:late<=0?'ontime':late<=RULES.graceMinutes*60000?'late':'expired',day,due,finishedAt}}
export function submitTask(s,id,taskId,finishedAt,{complete=true,minutes=0,assignmentDone=true,requestId=freshId()}={}){return mutate(s,d=>{kid(d,id);if(d.requests.some(r=>r.id===requestId))return d.requests.find(r=>r.id===requestId);if(d.ledger.some(e=>['chore','legacy-chore'].includes(e.kind)&&e.kidId===id&&e.taskDay===dayKey(finishedAt)&&e.taskId===taskId)||d.requests.some(r=>['chore','legacy-chore'].includes(r.type)&&r.kidId===id&&r.day===dayKey(finishedAt)&&r.taskId===taskId&&r.status==='pending'))fail('งานนี้บันทึกแล้ว');if(['piano','chess','taekwondo'].includes(taskId)&&minutes<20)complete=false;if(taskId==='homework'&&!assignmentDone)complete=false;const result=scoreTask(d,id,taskId,finishedAt,complete);const r={id:requestId,type:'chore',kidId:id,taskId,day:result.day,finishedAt,complete,minutes,assignmentDone,status:'pending',createdAt:Date.now(),ruleVersion:VERSION};d.requests.push(r);return r})}
function autoRepay(d,k,amount){const loan=d.loans.find(l=>l.kidId===k.id&&l.status==='open');if(!loan||amount<=0)return 0;const paid=Math.min(loan.remaining,Math.floor(amount/2),k.earned);k.earned-=paid;loan.remaining-=paid;loan.paid+=paid;entry(d,k.id,'repayment',-paid,{loanId:loan.id,source:'chore-auto'});if(!loan.remaining)loan.status='closed';return paid}
function grant(d,id,kind,amount,meta={}){const k=kid(d,id);k.earned+=amount;entry(d,id,kind,amount,meta);if(kind==='chore'||kind==='bonus'){k.xp=(k.xp||0)+amount;k.eggWarm=(k.eggWarm||0)+(kind==='bonus'?10:meta.status==='ontime'?3:0);if(kind==='chore'&&amount>0)d.tickets.push({id:meta.requestId,kidId:id,status:'ready'});if(kind==='chore')autoRepay(d,k,amount)}if(k.deficit){const recovered=Math.min(k.earned,k.deficit);k.earned-=recovered;k.deficit-=recovered;entry(d,id,'penalty recovery',-recovered,{source:kind})}}
export const PETS=['🦎','🐍','🦂','🕷️','🦇','🐗','🦉','🐙','🐺','🦈','🐊','🦅','🦏','🦑','🦍','🐆','🐅','🦁','🦣','🦖','🐉'];
const petNeed=k=>75+(k.pets||[]).length*60;
export function hatchPet(s,id){return mutate(s,d=>{const k=kid(d,id);if(k.eggWarm<petNeed(k))fail('ไข่ยังไม่พร้อมฟัก');const candidates=PETS.filter(e=>!(k.pets||[]).includes(e)),pet=candidates[Math.floor(Math.random()*candidates.length)]||PETS[Math.floor(Math.random()*PETS.length)];k.eggWarm-=petNeed(k);k.pets=[...(k.pets||[]),pet];k.pet ||=pet;k.petst ||= {};k.petst[pet]={f:Date.now(),p:Date.now(),w:Date.now(),c:0,b:Date.now()};audit(d,'hatch',{kidId:id,pet});return pet})}
export function carePet(s,id,action,ts=Date.now()){return mutate(s,d=>{const k=kid(d,id),pet=k.pet;if(!pet||!['feed','play','wash'].includes(action))fail('เลือกสัตว์และการดูแล');const st=(k.petst||{})[pet]||{f:ts,p:ts,w:ts,c:0,b:ts};st[{feed:'f',play:'p',wash:'w'}[action]]=ts;st.c=(st.c||0)+1;k.petst[pet]=st;return st})}
export function choosePet(s,id,pet){return mutate(s,d=>{const k=kid(d,id);if(!(k.pets||[]).includes(pet))fail('ยังไม่มีสัตว์ตัวนี้');k.pet=pet})}
export function startJourney(s,id,ts=Date.now()){return mutate(s,d=>{const k=kid(d,id),a=k.adventure||{level:0,completed:0,collection:{},session:null};if(a.session&&a.session.stage<3)return a.session;if(!k.pet)fail('ต้องฟักสัตว์ก่อน');const ticket=d.tickets.find(t=>t.kidId===id&&t.status==='ready');if(!ticket)fail('ต้องทำงานที่ได้แต้มเพื่อรับเสบียง');ticket.status='used';const session={id:freshId(),stage:0,level:a.level||0,pet:k.pet,startedAt:ts};k.adventure={...a,session};return session})}
export function completeJourneyStage(s,id,sessionId,stage){return mutate(s,d=>{const k=kid(d,id),a=k.adventure||fail('ยังไม่มีการผจญภัย'),session=a.session;if(!session||session.id!==sessionId||!Number.isInteger(stage)||stage<0||stage>2||stage>session.stage)fail('ลำดับด่านไม่ถูกต้อง');if(stage<session.stage)return a;if(stage===2){const prizes=['sprout','crystal','tent'],prize=prizes[(a.completed||0)%prizes.length];a.completed=(a.completed||0)+1;a.collection={...(a.collection||{}),[prize]:(a.collection?.[prize]||0)+1};session.prize=prize}session.stage++;return a})}
export function approveTask(s,requestId){return mutate(s,d=>{const r=d.requests.find(x=>x.id===requestId&&x.type==='chore')||fail('ไม่พบคำขอ');if(r.status==='approved')return r;if(r.status!=='pending')fail('คำขอนี้สิ้นสุดแล้ว');if(d.ledger.some(e=>e.kind==='chore'&&e.kidId===r.kidId&&e.taskDay===r.day&&e.taskId===r.taskId))fail('งานนี้ได้แต้มแล้ว');const result=scoreTask(d,r.kidId,r.taskId,r.finishedAt,r.complete&&r.assignmentDone&&(r.minutes>=20||!RULES.tasks[r.taskId].practice));r.status='approved';r.points=result.points;grant(d,r.kidId,'chore',result.points,{taskId:r.taskId,taskDay:r.day,status:result.status,finishedAt:r.finishedAt,requestId:r.id});const routines=activeTasks(d,r.day).filter(t=>t.routine);if(routines.length&&routines.every(t=>d.ledger.some(e=>e.kind==='chore'&&e.kidId===r.kidId&&e.taskDay===r.day&&e.taskId===t.id&&e.status==='ontime'))&&!d.ledger.some(e=>e.kind==='bonus'&&e.kidId===r.kidId&&e.taskDay===r.day))grant(d,r.kidId,'bonus',20,{taskDay:r.day,name:'กิจวัตรตรงเวลาครบ'});return r})}
export function rejectTask(s,id,reason=''){return mutate(s,d=>{const r=d.requests.find(x=>x.id===id&&x.type==='chore')||fail('ไม่พบคำขอ');if(r.status==='pending'){r.status='rejected';r.reason=reason}return r})}
export function settleLegacyChore(s,id,approve=false,full=false){const d=clone(validate(s)),r=d.requests.find(x=>x.id===id&&x.type==='legacy-chore')||fail('ไม่พบงานเดิมที่รอตรวจ');if(r.status!=='pending')return r;const points=approve?(full?r.fullPoints:r.proposedPoints):0;r.status=approve?'approved':'rejected';r.points=points;if(approve){const k=kid(d,r.kidId);k.earned+=points;k.xp=(k.xp||0)+points;if(points>0)d.tickets.push({id:r.id,kidId:k.id,status:'ready',legacy:true});entry(d,k.id,'legacy-chore',points,{requestId:r.id,taskId:r.taskId,taskDay:r.day,name:r.name,status:r.legacyStatus,ts:r.finishedAt,legacy:true});}if(d.legacy){d.legacy.pending=d.legacy.pending.filter(x=>x.id!==r.id);d.legacy.blockers=d.legacy.blockers.filter(x=>!x.startsWith('คำขอเก่าค้าง'));if(d.legacy.pending.length)d.legacy.blockers.push(`คำขอเก่าค้าง ${d.legacy.pending.length} รายการ`);d.legacy.blocked=d.legacy.blockers.length>0}validate(d);Object.assign(s,d);return r}
export function penalty(s,id,type,reason){const pts={screen:20,physical:30}[type];if(!pts||!String(reason).trim())fail('ระบุเหตุการณ์และเหตุผล');return mutate(s,d=>{const k=kid(d,id),parts=spend(k,Math.min(k.earned+k.borrowed,pts));const applied=parts.earned+parts.borrowed;k.deficit=(k.deficit||0)+pts-applied;entry(d,id,'penalty',-pts,{reason,type,nominal:pts,unpaid:pts-applied});audit(d,'penalty',{kidId:id,reason});return pts})}
export function adjust(s,id,amount,reason,corrects=null){if(!Number.isSafeInteger(amount)||!String(reason).trim())fail('จำนวนหรือเหตุผลไม่ถูกต้อง');return mutate(s,d=>{const k=kid(d,id);if(amount>=0)k.earned+=amount;else spend(k,-amount);entry(d,id,'adjustment',amount,{reason,corrects});audit(d,'adjustment',{kidId:id,reason})})}
function quotaUse(s,r,ts){const participants=r.participants||Object.keys(r.shares);if(['youtube','game'].includes(r.rewardId)){const day=dayKey(ts),week=weekKey(ts);return participants.some(id=>s.requests.filter(x=>x.status!=='cancelled'&&x.status!=='rejected'&&x.type==='reward'&&['youtube','game'].includes(x.rewardId)&&x.participants.includes(id)&&x.id!==r.id&&weekKey(x.ts)===week).length>=4||s.requests.some(x=>x.status!=='cancelled'&&x.status!=='rejected'&&x.type==='reward'&&['youtube','game'].includes(x.rewardId)&&x.participants.includes(id)&&x.id!==r.id&&dayKey(x.ts)===day))}if(['dinner','icecream'].includes(r.rewardId))return s.requests.filter(x=>x.status!=='cancelled'&&x.status!=='rejected'&&x.type==='reward'&&x.rewardId===r.rewardId&&x.id!==r.id&&weekKey(x.ts)===weekKey(ts)).length>=2;if(r.rewardId.startsWith('toy'))return participants.some(id=>s.requests.some(x=>x.status!=='cancelled'&&x.status!=='rejected'&&x.type==='reward'&&x.rewardId===r.rewardId&&x.participants.includes(id)&&x.id!==r.id&&ts<addMonths(x.ts,6)));return false}
function legacyQuotaUse(s,r,ts){const events=s.legacy?.quotaEvents||s.legacyAssets?.quotaEvents||[];if(!events.length)return false;const active=x=>x.status!=='cancelled'&&x.status!=='rejected'&&x.type==='reward';if(['youtube','game'].includes(r.rewardId))return r.participants.some(id=>{const old=events.filter(e=>e.kidId===id&&['youtube','game'].includes(e.rewardId)&&weekKey(e.ts)===weekKey(ts));const newer=s.requests.filter(x=>active(x)&&['youtube','game'].includes(x.rewardId)&&x.participants.includes(id)&&weekKey(x.ts)===weekKey(ts));return old.length+newer.length>=4||old.some(e=>dayKey(e.ts)===dayKey(ts))});if(['dinner','icecream'].includes(r.rewardId)){const old=events.filter(e=>e.rewardId===r.rewardId&&!e.inv&&weekKey(e.ts)===weekKey(ts));const newer=s.requests.filter(x=>active(x)&&x.rewardId===r.rewardId&&weekKey(x.ts)===weekKey(ts));return old.length+newer.length>=2}if(r.rewardId.startsWith('toy'))return r.participants.some(id=>events.some(e=>e.kidId===id&&e.rewardId===r.rewardId&&ts<addMonths(e.ts,6)));return false}
export function requestReward(s,rewardId,participants,shares,ts=Date.now(),requestId=freshId()){return mutate(s,d=>{if(d.requests.some(r=>r.id===requestId))return d.requests.find(r=>r.id===requestId);const reward=RULES.rewards[rewardId]||fail('ไม่มีรางวัล');participants=[...new Set(participants)];if(!participants.length||Object.keys(shares).some(id=>!participants.includes(id))||participants.reduce((n,id)=>n+Number(shares[id]||0),0)!==reward.cost||participants.some(id=>!Number.isSafeInteger(shares[id]||0)||(shares[id]||0)<0))fail('ส่วนจ่ายรวมไม่ตรงราคา');const r={id:requestId,type:'reward',rewardId,participants,shares,ts,day:dayKey(ts),status:'pending',reserved:{},ruleVersion:VERSION};if(quotaUse(d,r,ts)||legacyQuotaUse(d,r,ts))fail('โควตาเต็ม');for(const id of participants)r.reserved[id]=spend(kid(d,id),shares[id]||0,['sea','abroad','toy200','toy500','toy1000'].includes(rewardId));d.requests.push(r);return r})}
export function settleReward(s,id,approve=true,ts=Date.now()){return mutate(s,d=>{const r=d.requests.find(x=>x.id===id&&x.type==='reward')||fail('ไม่พบคำขอ');if(r.status!=='pending')return r;if(!approve){for(const [kidId,parts] of Object.entries(r.reserved))refund(kid(d,kidId),parts);r.status='rejected';return r}if(dayKey(ts)!==r.day&&['screen','dinner','icecream'].includes(RULES.rewards[r.rewardId].group))fail('คำขอข้ามวัน: ยกเลิกและขอใหม่');r.status='approved';for(const [kidId,parts] of Object.entries(r.reserved))entry(d,kidId,'reward',-(parts.earned+parts.borrowed),{rewardId:r.rewardId,requestId:r.id,parts});return r})}
export function cancelReward(s,id){return mutate(s,d=>{const r=d.requests.find(x=>x.id===id&&x.type==='reward')||fail('ไม่พบคำขอ');if(r.status!=='pending')return r;for(const [kidId,p] of Object.entries(r.reserved))refund(kid(d,kidId),p);r.status='cancelled';return r})}
export function openDeposit(s,id,amount,days,ts=Date.now()){if(!Number.isSafeInteger(amount)||amount<100||amount%100||![7,30].includes(days))fail('ฝากขั้นต่ำ 100 เพิ่มทีละ 100 เลือก 7 หรือ 30 วัน');return mutate(s,d=>{spend(kid(d,id),amount,true);const dep={id:freshId(),kidId:id,principal:amount,original:amount,days,rate:days===7?1:5,openedAt:ts,dueAt:ts+days*DAY,status:'open'};d.deposits.push(dep);entry(d,id,'deposit principal',-amount,{depositId:dep.id,ts});return dep})}
export function withdrawDeposit(s,id,amount,ts=Date.now()){return mutate(s,d=>{const dep=d.deposits.find(x=>x.id===id&&x.status==='open')||fail('ไม่พบเงินฝาก');if(!Number.isSafeInteger(amount)||amount<=0||amount>dep.principal)fail('จำนวนถอนผิด');const k=kid(d,dep.kidId);dep.principal-=amount;k.earned+=amount;entry(d,k.id,'deposit principal',amount,{depositId:id,early:ts<dep.dueAt,ts});if(!dep.principal)dep.status='closed';return dep})}
export function matureDeposits(s,ts=Date.now()){return mutate(s,d=>{let count=0;for(const dep of d.deposits.filter(x=>x.status==='open'&&x.dueAt<=ts)){const interest=Math.floor(dep.principal*dep.rate/100);const k=kid(d,dep.kidId);k.earned+=dep.principal+interest;entry(d,k.id,'deposit principal',dep.principal,{depositId:dep.id,ts});entry(d,k.id,'interest',interest,{depositId:dep.id,ts});dep.principal=0;dep.status='matured';count++}return count})}
export function openLoan(s,id,amount,ts=Date.now()){if(!Number.isSafeInteger(amount)||amount<=0||amount>300)fail('ยืมได้ไม่เกิน 300');return mutate(s,d=>{if(d.loans.some(l=>l.kidId===id&&l.status==='open'))fail('ยังมีหนี้');const k=kid(d,id),total=Math.ceil(amount*1.1),loan={id:freshId(),kidId:id,principal:amount,total,remaining:total,paid:0,openedAt:ts,dueAt:ts+14*DAY,status:'open'};d.loans.push(loan);k.borrowed+=amount;entry(d,id,'loan principal',amount,{loanId:loan.id,ts});return loan})}
export function repayLoan(s,id,amount){return mutate(s,d=>{const loan=d.loans.find(l=>l.id===id&&l.status==='open')||fail('ไม่พบหนี้');const k=kid(d,loan.kidId);if(!Number.isSafeInteger(amount)||amount<=0||amount>loan.remaining||amount>k.earned)fail('ยอดคืนไม่ถูกต้อง');k.earned-=amount;loan.remaining-=amount;loan.paid+=amount;entry(d,k.id,'repayment',-amount,{loanId:id});if(!loan.remaining)loan.status='closed';return loan})}
export function transfer(s,from,to,amount){return mutate(s,d=>{if(from===to)fail('ผู้รับซ้ำ');const a=kid(d,from),b=kid(d,to);spend(a,amount,true);b.earned+=amount;const pair=freshId();entry(d,from,'transfer',-amount,{pair,to});entry(d,to,'transfer',amount,{pair,from});return pair})}
export function migrationPreview(raw){const issues=[];const kids=(raw.kids||[]).map(k=>({id:k.id,name:k.name,daily:Number(k.points||0),extra:Number(k.extra||0),total:Number(k.points||0)+Number(k.extra||0),petFields:['pets','pet','petst','eggWarm','xp','adventure'].filter(x=>k[x]!==undefined)}));for(const k of kids)if(!Number.isSafeInteger(k.total))issues.push(`ยอด ${k.name} ผิดรูปแบบ`);const bank=[...(raw.bank||[]),...(raw.kids||[]).flatMap(k=>(k.bank||[]).map(b=>({...b,kidId:k.id})))];for(const b of bank)if(!legacyBankRecord(b,b.kidId))issues.push(`สัญญาเก่า ${b.id||'?'} (${b.kind}) ยังแปลงไม่ได้`);for(const p of raw.pending||[])if(p.type!=='chore'||!p.id||!p.kidId||!Number.isFinite(Number(p.ts))||!Number.isSafeInteger(Number(p.pts))||!Number.isSafeInteger(Number(p.full)))issues.push(`คำขอค้าง ${p.id||'?'} ยังแปลงไม่ได้`);return {version:VERSION,kids,total:kids.reduce((n,k)=>n+k.total,0),ledgerCount:(raw.log||[]).length,issues,ready:!issues.length}}
export function migrateSnapshot(raw,asOf=Date.now(),migrationAt=asOf){const preview=migrationPreview(raw);if(!preview.ready)fail(preview.issues.join('; '));const {state,blocked}=stageLegacySnapshot(raw,asOf,migrationAt);if(blocked)fail(state.legacy.blockers.join('; '));state.legacyAssets={petart:state.legacy.petart,quotaEvents:state.legacy.quotaEvents};delete state.legacy;for(const k of state.kids){delete k.pin;delete k.points;delete k.extra;delete k.bank}state.migrations=[{id:'legacy-to-pilot-1',at:migrationAt,sourceTotals:preview.kids}];return validate(state)}

// Local staging import only. It keeps unresolved old contracts and requests
// visible, but blocks new transactions until those records are reconciled.
export function stageLegacySnapshot(input,asOf=Date.now(),migrationAt=asOf){
  const raw=input?.raw||input;
  if(!raw||!Array.isArray(raw.kids)||!raw.kids.length)fail('snapshot ไม่มีข้อมูลเด็ก');
  const ids=new Set(),s=newState([]),balances=[];
  s.kids=raw.kids.map(k=>{
    if(!k.id||ids.has(k.id))fail('รหัสเด็กซ้ำหรือหาย');ids.add(k.id);
    const daily=Number(k.points??0),extra=Number(k.extra??0),total=daily+extra;
    if(!Number.isSafeInteger(daily)||!Number.isSafeInteger(extra)||!Number.isSafeInteger(total))fail('ยอดแต้มเก่าไม่ใช่จำนวนเต็ม');
    balances.push({kidId:k.id,name:k.name,daily,extra,total});
    return {...clone(k),earned:Math.max(total,0),borrowed:0,deficit:Math.max(-total,0),
      pets:Array.isArray(k.pets)?clone(k.pets):[],petst:clone(k.petst||{}),
      xp:Number(k.xp||0),eggWarm:Number(k.eggWarm||0)};
  });
  const bank=[...(Array.isArray(raw.bank)?clone(raw.bank):[]),...s.kids.flatMap(k=>(Array.isArray(k.bank)?k.bank:[]).map(b=>({kidId:k.id,...clone(b)})))];
  const pending=Array.isArray(raw.pending)?clone(raw.pending):[];
  const seenBank=new Set(),unmappedBank=[];
  for(const b of bank){const dep=legacyBankRecord(b,b.kidId);if(!dep||seenBank.has(b.id))unmappedBank.push(b);else{s.deposits.push(dep);seenBank.add(b.id)}}
  const unmappedPending=[];
  for(const p of pending){const proposedPoints=Number(p.pts),fullPoints=Number(p.full),finishedAt=Number(p.ts);if(p.type!=='chore'||!p.id||!ids.has(p.kidId)||!Number.isFinite(finishedAt)||!Number.isSafeInteger(proposedPoints)||!Number.isSafeInteger(fullPoints)||proposedPoints<0||fullPoints<proposedPoints||s.requests.some(r=>r.id===p.id)){unmappedPending.push(p);continue}const taskId=legacyTaskId(p.name);s.requests.push({id:p.id,type:'legacy-chore',kidId:p.kidId,taskId,day:dayKey(finishedAt),finishedAt,name:p.name,legacyStatus:p.status||'',proposedPoints,fullPoints,status:'pending',legacy:true,ruleVersion:'legacy'})}
  s.ledger=(raw.log||[]).map(l=>{const item={...clone(l),legacy:true,ruleVersion:'legacy'};if(item.kind==='chore'&&Number.isFinite(Number(item.ts))){item.taskId=legacyTaskId(item.name);item.taskDay=dayKey(Number(item.ts))}return item});
  const quotaEvents=s.ledger.filter(l=>l.kind==='reward'&&Number.isFinite(Number(l.ts))).map(l=>({id:l.id,kidId:l.kidId,rewardId:legacyRewardId(l.name),ts:Number(l.ts),inv:!!l.inv||/\(หารกัน\)/.test(String(l.name||''))})).filter(x=>x.rewardId);
  s.tickets=(raw.adventureTickets||[]).map(t=>({...clone(t),status:t.state==='ready'?'ready':'used'}));
  const blockers=[];
  if(unmappedBank.length)blockers.push(`สัญญาธนาคารเก่า ${unmappedBank.length} รายการยังแปลงไม่ได้`);
  if(unmappedPending.length)blockers.push(`คำขอเก่าค้าง ${unmappedPending.length} รายการยังแปลงไม่ได้`);
  if(s.ledger.some(l=>l.kind==='chore'&&Number.isFinite(Number(l.ts))&&dayKey(Number(l.ts))===dayKey(asOf)&&!l.taskId))blockers.push('งานเก่าวันนี้บางรายการจับคู่กับกฎใหม่ไม่ได้');
  if(s.ledger.some(l=>l.kind==='reward'&&Number.isFinite(Number(l.ts))&&weekKey(Number(l.ts))===weekKey(asOf)&&!legacyRewardId(l.name)))blockers.push('รางวัลเก่าสัปดาห์นี้บางรายการจับคู่โควตาไม่ได้');
  if(s.ledger.some(l=>l.kind==='reward'&&Number.isFinite(Number(l.ts))&&Number(l.ts)>=addMonths(asOf,-6)&&!legacyRewardId(l.name)))blockers.push('รางวัลเก่าใน 6 เดือนบางรายการจับคู่โควตาไม่ได้');
  if(s.ledger.length>=600)blockers.push('ประวัติ 600 รายการขึ้นไปต้องตรวจความครบ');
  if(s.kids.some(k=>k.adventure?.session&&k.adventure.session.stage<3))blockers.push('เกมเก่าค้างระหว่างด่าน');
  s.legacy={blocked:blockers.length>0,blockers,bank,pending,quotaEvents,
    petart:Object.assign({},...(Object.values(raw.petartDocs||{}).map(doc=>clone(doc||{})))),
    sourceCounts:{kids:s.kids.length,log:s.ledger.length,tickets:s.tickets.length},
    note:'สำเนาทดลองในเครื่อง ไม่ได้เขียน Firebase'};
  s.migrations=[{id:'legacy-stage-1',at:migrationAt,sourceBalances:balances}];
  validate(s);
  return {state:s,balances,blocked:s.legacy.blocked};
}
